name: Deploy Code to EC2

on:
  push:
    branches:
      - main  
jobs:
  deploy-ec2:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_ID }}
          aws configure set aws_secret_access_key ${{ secrets.ACCESS_SECRET }}
          aws configure set default.region us-east-1

      - name: Initialize SSH
        run: |
          ssh-keyscan ec2-34-239-105-198.compute-1.amazonaws.com >> ~/.ssh/known_hosts 

      - name: Deploy code to EC2
        run: |
          echo "${{ secrets.EC2_KEY_PAIR }}" > student.pem && chmod 400 student.pem
          scp -i "student.pem" -r ./codes ubuntu@ec2-34-239-105-198.compute-1.amazonaws.com:/home/ubuntu/

